# configuration for "master" branch
- branches:
    only:
      - master

  version: 1.1.{build}
  image: Visual Studio 2019

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'

  configuration:
    - Release

  environment:
    TreatWarningsAsErrors: false

  skip_tags: true

  cache:
    - packages -> **\packages.config

  before_build:
    - dotnet restore Datory.sln

  build:
    project: Datory.sln # path to Visual Studio solution or project
    publish_nuget: true

  deploy:
    provider: NuGet
    server: # remove to push to NuGet.org
    api_key:
      secure: 9It7tTZD6eJFdc3/dsjeZ0SXgevLQW57PKbR18aMlOisCBdKQOWWOqBYn1UEgWej
    skip_symbols: false
    symbol_server: # remove to push symbols to SymbolSource.org
    artifact: /Datory.*\.nupkg/

# configuration for "dev" branch
- branches:
    only:
      - dev

  version: 1.1.{build}-beta
  image: Visual Studio 2019

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  platform: Any CPU

  configuration:
    - Release

  environment:
    TreatWarningsAsErrors: false

  skip_tags: true

  cache:
    - packages -> **\packages.config

  before_build:
    - nuget restore Datory.sln

  build:
    project: Datory.sln # path to Visual Studio solution or project
    publish_nuget: true

  deploy:
    provider: NuGet
    server: # remove to push to NuGet.org
    api_key:
      secure: 9It7tTZD6eJFdc3/dsjeZ0SXgevLQW57PKbR18aMlOisCBdKQOWWOqBYn1UEgWej
    skip_symbols: false
    symbol_server: # remove to push symbols to SymbolSource.org
    artifact: /Datory.*\.nupkg/
